# Site settings
title: Pollock Documentation
description: >
  Pollock - Make Pools !
baseurl: "/Pollock" # the subpath of your site
url: "http://pollock.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Do not watch all folders
exclude:
  - node_modules
  - apidoc
  - public
  - public/**/*
  - .git
  - .sass-cache
  - bower_components/**/*.md
  - bower_components/**/*.html
